# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 12:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=127, unique=True, validators=[django.core.validators.RegexValidator(message='Only lower case letters, numbers, slashes (/) and dashes (-) allowed.', regex='[a-z0-9-]+')])),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_internal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=127, unique=True, validators=[django.core.validators.RegexValidator(message='Only lower case letters, numbers, slashes (/) and dashes (-) allowed.', regex='[a-z0-9-]+')])),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('kontena', 'Kontena Grid'), ('aws-ess', 'AWS ElasticSearch Service'), ('aws-rds', 'AWS RDS'), ('bunch', 'Just a bunch of nodes')], default='kontena', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('role', models.CharField(choices=[('general', 'General purpose'), ('lb', 'Load Balancer'), ('bastion', 'Bastion Host'), ('app', 'Application Node')], default='general', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='cmdb.Grid')),
                ('paid_for_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='cmdb.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=127, unique=True, validators=[django.core.validators.RegexValidator(message='Only lower case letters, numbers, slashes (/) and dashes (-) allowed.', regex='[a-z0-9-]+')])),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='cmdb.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(blank=True, max_length=127, validators=[django.core.validators.RegexValidator(message='Only lower case letters, numbers, slashes (/) and dashes (-) allowed.', regex='[a-z0-9-]+')])),
                ('canonical_name', models.CharField(blank=True, max_length=127, unique=True, validators=[django.core.validators.RegexValidator(message='Only lower case letters, numbers, slashes (/) and dashes (-) allowed.', regex='[a-z0-9-]+')])),
                ('role', models.CharField(choices=[('backend', 'Web backend or API'), ('frontend', 'Web frontend'), ('database', 'Database'), ('queue', 'Message queue'), ('cache', 'Cache or auxiliary database'), ('worker', 'Background worker')], default='backend', max_length=8)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depends_on', models.ManyToManyField(blank=True, related_name='_service_depends_on_+', to='cmdb.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=127, unique=True, validators=[django.core.validators.RegexValidator(message='Only lower case letters, numbers, slashes (/) and dashes (-) allowed.', regex='[a-z0-9-]+')])),
                ('name', models.CharField(max_length=255)),
                ('environment', models.CharField(choices=[('staging', 'Staging'), ('production', 'Production')], default='staging', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stacks', to='cmdb.Grid')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stacks', to='cmdb.Project')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='cmdb.Stack'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set([('stack', 'slug')]),
        ),
    ]
