from django.core.validators import RegexValidator


validate_slug = RegexValidator(
    regex=r'[a-z0-9-]+',
    message='Only lower case letters, numbers, slashes (/) and dashes (-) allowed.'
)


class CommonFields:
    slug = dict(
        blank=True,  # actually not, but autogenerated anyway
        max_length=127,
        validators=[validate_slug],
    )
